<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autores, anio)>
    <!ELEMENT autores (autor+)>
    <!ELEMENT autor (nombre, apellido, nacionalidad)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
    <!ELEMENT idioma (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT nacionalidad (#PCDATA)*>
    <!ATTLIST libro idlibro ID #REQUIRED>
    <!ATTLIST libro genero CDATA #IMPLIED>
    <!ATTLIST libro idioma CDATA "Español">
    <!ATTLIST libro formato (impreso|digital) "impreso">
    <!ATTLIST libro ref IDREFS #IMPLIED>
]>
<biblioteca>
    <libro idlibro="libro1" genero="novela" idioma="Español" formato="digital" >
        <titulo>Titulo del Libro</titulo>
        <autores>
            <autor>
                <nombre>Juan</nombre>
                <apellido>Perez</apellido>
                <nacionalidad>Española</nacionalidad>
            </autor>
        </autores>
         <anio>2024</anio>
    </libro>
</biblioteca>