=== CrisMatVeg/111LMSGIProyectoLMSGI/ud4/01/01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Declaraci贸n tipos simples-->
    <!-- Declaraci贸n tipos complejos-->
    <xs:complexType name="tipoFecha">
        <xs:sequence>
            <xs:element name="dia" type="xs:string" />
            <xs:element name="mes" type="xs:string" />
            <xs:element name="anio" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!-- Declaraci贸n del tipo de "fichero" -->
    <xs:complexType name="tipoFichero">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="tipo" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!-- Declaraci贸n de elementos-->
    <xs:element name="mail">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="remitente" type="xs:string" />
                <xs:element name="destinatarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="destinatario" type="xs:string" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fecha" type="tipoFecha" />
                <xs:element name="asunto" minOccurs="0" type="xs:string" />
                <xs:element name="mensaje">
                    <xs:complexType mixed="true">
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="p">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="strong">
                                            <xs:complexType mixed="true" />
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="h2">
                                <xs:complexType mixed="true" />
                            </xs:element>
                            <xs:element name="h3">
                                <xs:complexType mixed="true" />
                            </xs:element>
                            <xs:element name="strong">
                                <xs:complexType mixed="true" />
                            </xs:element>
                            <xs:element name="ul">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="li" maxOccurs="unbounded">
                                            <xs:complexType mixed="true" />
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ficheros_adjuntos" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fichero" type="tipoFichero" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CrisMatVeg/111LMSGIProyectoLMSGI/ud4/01/01.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
Nombre: Cristian Mateos
Descripción: Información de un mail
Fecha:25-11-2024
-->
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
    <remitente>remitente@example.com</remitente>
    <destinatarios>
        <destinatario>destinatario1@example.com</destinatario>
        <destinatario>destinatario2@example.com</destinatario>
    </destinatarios>
    <fecha>
        <dia>12</dia>
        <mes>03</mes>
        <anio>2025</anio>
    </fecha>
    <asunto>Ejemplo de correo en XML</asunto>
    <mensaje>
        <h2>Encabezado del mensaje</h2>
        <p>Este es un <strong>ejemplo</strong> de mensaje en XML.</p>
        <ul>
            <li>Punto 1</li>
            <li>Punto 2</li>
        </ul>
    </mensaje>
    <ficheros_adjuntos>
        <fichero>
            <nombre>documento.pdf</nombre>
            <tipo>application/pdf</tipo>
        </fichero>
        <fichero>
            <nombre>imagen.jpg</nombre>
            <tipo>image/jpeg</tipo>
        </fichero>
    </ficheros_adjuntos>
</mail>
